version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  postgres_db:

